# Generated by Django 2.1 on 2018-08-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180815_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.ImageField(upload_to='blog/static/blog/images/%Y/%m/%d/'),
        ),
    ]
