# Generated by Django 2.1 on 2018-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180815_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.ImageField(upload_to='blog/static/blog/%Y/%m/%d/'),
        ),
    ]
