# Generated by Django 2.1 on 2018-08-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180817_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='image', max_length=150),
            preserve_default=False,
        ),
    ]
