# Generated by Django 2.1 on 2018-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180817_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='caption',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
