# Generated by Django 2.1 on 2018-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180817_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(blank=True, default='default_content'),
        ),
    ]
