# Generated by Django 2.1 on 2018-08-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180817_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
